default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: sqlite3
  timeout: 5000
  database: db/development.sqlite3

test:
  adapter: sqlite3
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: emails_hexlet_task_production
  username: emails_hexlet_task
  password: <%= ENV["EMAILS_HEXLET_TASK_DATABASE_PASSWORD"] %>
